### ISSUE TITLE
[Setting] 개발 생산성 향상을 위한 Git Hooks 설정

### ISSUE THREAD

**Issue by ParkJungYoon** [depromeet/13th-1team-backend#11]
## 💡 이슈 내용
- 프로젝트에 Spotless 등을 통해 Lint를 정하게 되면 반복 작업이 발생
  - 매번 Gradle Task Spotless Apply / Spotless Check를 통해 Lint가 맞는지 확인하고
  - 커밋 전에 수동으로 적용해야함.
- 이를 잊어버릴 시 ci test 실패. 휴먼 에러를 줄이기 위해 자동화 필요.
- 이런 과정을 자동화해 매 커밋마다 1~2초를 줄이고, 팀원 전부 앞으로의 개발 효율을 위해 설정

## ✅ 상세 작업 내용
- [x] Git Hooks 설정
- 관련 이슈 : #4

## 📌 Reference
- [생산성 향상을 위한 Git Hooks](https://wnwngus.tistory.com/m/71)
- [Gradle auto-installing pre-commit hook](https://gist.github.com/KenVanHoeylandt/c7a928426bce83ffab400ab1fd99054a#file-install-git-hooks-gradle)

**Comment by ImNM** [comment]
만들어주시면 잘 쓰겠습니다 
감사합니다

**Comment by ParkJungYoon** [comment]
어맛! 천천히 하려고 했는데 기대에(?) 힘입어 재빠르게 해봐야겠네용! ㅋㅋㅋㅋㅋ 넵 좋습니다🙌
