### ISSUE TITLE
[Bug] yml 파일이 인식되지 않는 문제

### ISSUE THREAD

**Issue by likelasttime** [depromeet/13th-1team-backend#21]
## 🐛 버그 내용
- [x] Module-API를 실행하니 application-api.yml 파일이 인식되지 않음

## 참고
https://oingdaddy.tistory.com/464

**Comment by ParkJungYoon** [comment]
application.yml 파일로 문제 해결

![스크린샷 2023-05-28 오후 2 34 05](https://github.com/depromeet/jalingobi-server/assets/97580782/bfaeecc9-4f08-4982-9a7c-26c19147cf64)
