### ISSUE TITLE
[Refactor] 사용자가 참여한 챌린지 조회 반환 값 DTO로 리팩토링

### ISSUE THREAD

**Issue by ParkJungYoon** [depromeet/13th-1team-backend#225]
## 🐛 버그 내용
- [x] mypage/challenges 에서도 JSON 직렬화 관련 에러남. 해결하자~

## 서버 로그 or 스크린샷

<img width="595" alt="image" src="https://github.com/depromeet/jalingobi-server/assets/97580782/da59ee19-2825-4483-8c01-9cb4fcb65bbc">

![image](https://github.com/depromeet/jalingobi-server/assets/97580782/45180747-0a94-4a46-923a-ecfd9a6b272f)

**Comment by likelasttime** [comment]
[양방향 순환참조 해결하기](https://dev-coco.tistory.com/133)
문제가 발생하는 부분에 DTO를 사용하면 될 것 같아요
