### ISSUE TITLE
[Refactor] 패키지 구조 및 클래스 위치 변경

### ISSUE THREAD

**Issue by jjddhh** [depromeet/13th-1team-backend#27]
## ⚙️ 리팩토링 내용
- 현재 설정 파일들 Module-API에 몰아넣음. 조정 필요

## ✅ 상세 작업 내용
- [x] 파일 위치 조정

**Comment by ParkJungYoon** [comment]
전체적인 구조 잡힌 이후에 리팩토링 예정
