### ISSUE TITLE
[Bug] 댓글 생성, 삭제 에러 해결

### ISSUE THREAD

**Issue by likelasttime** [depromeet/13th-1team-backend#384]
## 🐛 버그 내용
- [ ] 댓글 생성자가 제대로 출력되지 않음
- [ ] 댓글 삭제 시 권한을 확인하는 비즈니스 로직이 잘못됨

**Comment by ParkJungYoon** [comment]
🕵️ 동호님 사칭 사건(?)

![image](https://github.com/depromeet/jalingobi-server/assets/97580782/d2a8981d-c944-4fd8-946a-82caa61fb626)
